// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UFC_API.Data;

#nullable disable

namespace UFC_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524154005_AddFightersWithSeedData")]
    partial class AddFightersWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UFC_API.Models.Fighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Fighters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 35,
                            Name = "Jon Jones",
                            Nickname = "Bones",
                            Rank = 1,
                            Weight = 205f
                        },
                        new
                        {
                            Id = 2,
                            Age = 33,
                            Name = "Israel Adesanya",
                            Nickname = "The Last Stylebender",
                            Rank = 2,
                            Weight = 185f
                        },
                        new
                        {
                            Id = 3,
                            Age = 34,
                            Name = "Khabib Nurmagomedov",
                            Nickname = "The Eagle",
                            Rank = 3,
                            Weight = 155f
                        },
                        new
                        {
                            Id = 4,
                            Age = 34,
                            Name = "Conor McGregor",
                            Nickname = "Notorious",
                            Rank = 4,
                            Weight = 170f
                        },
                        new
                        {
                            Id = 5,
                            Age = 41,
                            Name = "Stipe Miocic",
                            Rank = 5,
                            Weight = 240f
                        },
                        new
                        {
                            Id = 6,
                            Age = 35,
                            Name = "Alexander Volkanovski",
                            Nickname = "The Great",
                            Rank = 6,
                            Weight = 145f
                        },
                        new
                        {
                            Id = 7,
                            Age = 34,
                            Name = "Charles Oliveira",
                            Nickname = "Do Bronx",
                            Rank = 7,
                            Weight = 155f
                        },
                        new
                        {
                            Id = 8,
                            Age = 32,
                            Name = "Max Holloway",
                            Nickname = "Blessed",
                            Rank = 8,
                            Weight = 145f
                        },
                        new
                        {
                            Id = 9,
                            Age = 37,
                            Name = "Francis Ngannou",
                            Nickname = "The Predator",
                            Rank = 9,
                            Weight = 265f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
